from pathlib import Path

BASE_DIR = Path(__file__).parent

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
FPS = 60

GRAVITY = 0.6
JUMP_STRENGTH = -12
PLAYER_SPEED = 5

# Shorter hitbox so Theo can walk under floating platforms
PLAYER_HITBOX_HEIGHT = 45
PLAYER_HITBOX_WIDTH_RATIO = 0.65
PLAYER_PICKUP_WIDTH = 72
PLAYER_PICKUP_HEIGHT = 50

GRAPHICS_PATH = BASE_DIR / "graphics"
FONT_PATH = BASE_DIR / "PixelGame.otf"
UI_FONT_SIZE = 14

PLATFORM_COLOR = "#D4956A"
PLATFORM_BORDER = "#4A2C1A"
PLATFORM_HIGHLIGHT = "#F2C896"
PLATFORM_SHADOW = "#2E1A0E"
