from pathlib import Path

BASE_DIR = Path(__file__).parent

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
FPS = 60

GRAVITY = 0.6
JUMP_STRENGTH = -12
PLAYER_SPEED = 5

GRAPHICS_PATH = BASE_DIR / "graphics"
FONT_PATH = BASE_DIR / "PixelGame.otf"

PLATFORM_COLOR = "#D4956A"
PLATFORM_BORDER = "#4A2C1A"
PLATFORM_HIGHLIGHT = "#F2C896"
PLATFORM_SHADOW = "#2E1A0E"
